./spl $HOME/myexpos/os_code/Stage22/boot_module.spl
./spl $HOME/myexpos/os_code/Stage22/console_int.spl
./spl $HOME/myexpos/os_code/Stage22/device_manager_module.spl
./spl $HOME/myexpos/os_code/Stage22/disk_int.spl
./spl $HOME/myexpos/os_code/Stage22/excep_handler.spl
./spl $HOME/myexpos/os_code/Stage22/exec_int.spl
./spl $HOME/myexpos/os_code/Stage22/exit_int.spl
./spl $HOME/myexpos/os_code/Stage22/memory_man_mod.spl
./spl $HOME/myexpos/os_code/Stage22/os_start.spl
./spl $HOME/myexpos/os_code/Stage22/process_man_mod.spl
./spl $HOME/myexpos/os_code/Stage22/read_int.spl
./spl $HOME/myexpos/os_code/Stage22/resource_manager_module.spl
./spl $HOME/myexpos/os_code/Stage22/schedular_module.spl
./spl $HOME/myexpos/os_code/Stage22/timer_int.spl
./spl $HOME/myexpos/os_code/Stage22/write_int.spl
./spl $HOME/myexpos/os_code/Stage22/fork_int.spl
./spl $HOME/myexpos/os_code/Stage22/int11.spl
./spl $HOME/myexpos/os_code/Stage22/int13.spl
./spl $HOME/myexpos/os_code/Stage22/int14.spl
./spl $HOME/myexpos/os_code/Stage22/shutdown_int.spl