./spl $HOME/myexpos/os_code/Stage27/excep_handler.spl
./spl $HOME/myexpos/os_code/Stage27/os_start.spl
./spl $HOME/myexpos/os_code/Stage27/MOD0_resource_manager.spl
./spl $HOME/myexpos/os_code/Stage27/MOD1_process_manager.spl
./spl $HOME/myexpos/os_code/Stage27/MOD2_memory_manager.spl
./spl $HOME/myexpos/os_code/Stage27/MOD3_file_manager.spl
./spl $HOME/myexpos/os_code/Stage27/MOD4_device_manager.spl
./spl $HOME/myexpos/os_code/Stage27/MOD5_schedular.spl
./spl $HOME/myexpos/os_code/Stage27/MOD6_pager_mod.spl
./spl $HOME/myexpos/os_code/Stage27/MOD7_boot_module.spl
./spl $HOME/myexpos/os_code/Stage27/int4.spl
./spl $HOME/myexpos/os_code/Stage27/int5.spl
./spl $HOME/myexpos/os_code/Stage27/int6_read.spl
./spl $HOME/myexpos/os_code/Stage27/int7_write.spl
./spl $HOME/myexpos/os_code/Stage27/int8_fork.spl
./spl $HOME/myexpos/os_code/Stage27/int9_exec.spl
./spl $HOME/myexpos/os_code/Stage27/int10_exit.spl
./spl $HOME/myexpos/os_code/Stage27/int11.spl
./spl $HOME/myexpos/os_code/Stage27/int12.spl
./spl $HOME/myexpos/os_code/Stage27/int13.spl
./spl $HOME/myexpos/os_code/Stage27/int14.spl
./spl $HOME/myexpos/os_code/Stage27/int15_shutdown.spl
./spl $HOME/myexpos/os_code/Stage27/int16.spl
./spl $HOME/myexpos/os_code/Stage27/int17.spl
./spl $HOME/myexpos/os_code/Stage27/int_console.spl
./spl $HOME/myexpos/os_code/Stage27/int_disk.spl
./spl $HOME/myexpos/os_code/Stage27/int_timer.spl
