./spl $HOME/myexpos/os_code/Stage20/boot_module.spl
./spl $HOME/myexpos/os_code/Stage20/console_int.spl
./spl $HOME/myexpos/os_code/Stage20/device_manager_module.spl
./spl $HOME/myexpos/os_code/Stage20/disk_int.spl
./spl $HOME/myexpos/os_code/Stage20/excep_handler.spl
./spl $HOME/myexpos/os_code/Stage20/exec_int.spl
./spl $HOME/myexpos/os_code/Stage20/exit_int.spl
./spl $HOME/myexpos/os_code/Stage20/memory_man_mod.spl
./spl $HOME/myexpos/os_code/Stage20/os_start.spl
./spl $HOME/myexpos/os_code/Stage20/process_man_mod.spl
./spl $HOME/myexpos/os_code/Stage20/read_int.spl
./spl $HOME/myexpos/os_code/Stage20/resource_manager_module.spl
./spl $HOME/myexpos/os_code/Stage20/schedular_module.spl
./spl $HOME/myexpos/os_code/Stage20/timer_int.spl
./spl $HOME/myexpos/os_code/Stage20/write_int.spl
./spl $HOME/myexpos/os_code/Stage20/fork_int.spl